#! /usr/bin/env python

import re
import os
import subprocess as sub

WARNING  = '\033[93m'
ENDC     = '\033[0m'
BRANCHES = ["master", "development", "staging"]

try:
    if os.path.exists("./.git"):
        format_b = lambda b: re.sub('[ *]', '', b)
        result   = sub.check_output("git branch", stderr=sub.STDOUT, shell=True)
        branches = map(format_b, result.split('\n'))
        is_hhd   = reduce(lambda t, b: t and b in branches, BRANCHES)

        if is_hhd:
            match     = re.search('\*\s\w+', result)
            branch    = match.group(0)
            formatted = format_b(branch)

            print; print WARNING + "HHD REPOSITORY!\n\nYOU ARE ON: " + formatted + ENDC; print
except:
    pass
