#! /usr/bin/env python

import re
import os
import subprocess as sub

STARTC = '\033[95m'
ENDC   = '\033[0m'

try:
    if os.path.exists("./.git"):
        result = sub.check_output("git branch", stderr=sub.STDOUT, shell=True)
        match  = re.search('\*\s\w+', result)
        branch = match.group(0)
        formatted = branch.replace("* ", "")
        print; print STARTC + "GIT REPOSITORY. YOU ARE ON: " + formatted + ENDC; print
except:
    pass
